CREATE TABLE products (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
sku VARCHAR(100) UNIQUE,
link TEXT,
org_price DECIMAL(12,2),
cur_price DECIMAL(12,2),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE enemies (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
domain VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE product_crawls (
id INT AUTO_INCREMENT PRIMARY KEY,
prod_id INT NOT NULL,
enemy_id INT NOT NULL,
link TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (prod_id) REFERENCES products(id) ON DELETE CASCADE,
FOREIGN KEY (enemy_id) REFERENCES enemies(id) ON DELETE CASCADE
);

CREATE TABLE product_crawl_logs (
id INT AUTO_INCREMENT PRIMARY KEY,
product_crawl_id INT NOT NULL,
name VARCHAR(255) NOT NULL,
price DECIMAL(12,2),
timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
other_data JSON,
FOREIGN KEY (product_crawl_id) REFERENCES product_crawls(id) ON DELETE CASCADE
);